### ISSUE TITLE
As a server admin, I want to OPTIONALLY be able allow users to sign up but require my OK to finally be on my server.

### ISSUE THREAD

**Issue by em1i** [CMPUT404-Social-Distribution-Project/mondaylab-cmput404-project#27]

**Comment by nervuna** [comment]
Implementation: authors have a field called **_is_active_**. If **_is_active_** is _False_, then the author has to wait for the server admin to make it _True_ (this can be done in the admin panel). Right now when registering, authors will always have this field as _True_. But we need to figure out a way that would allow server admins to change a setting such that when registering, the django backend will check if this 'setting' should keep **_is_active_** as always True or always False. The issue is where should we put this 'setting'? In the front end? or in the backend, for example, when creating a superuser through the django interface?

**Comment by nervuna** [comment]
Finished as of  #66
